language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2
before_script:
  - bin/setup
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: ac82785a8b72ce12a4778ca56e43bf844cefbffcfa533eebc103fb090f4cdc23
